services:
  - type: web
    name: bexo
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXTAUTH_URL
        value: https://bexo.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
